version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "sbpdvb/terraform-aws-mcaf-glue"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "sbpdvb/terraform-aws-mcaf-glue"
